# Generated by Django 5.2.7 on 2025-10-05 21:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название факультета')),
                ('code', models.CharField(default='TEMP', max_length=10, unique=True, verbose_name='Код факультета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('code', models.CharField(default='TEMP', max_length=20, unique=True, verbose_name='Код группы')),
                ('course', models.IntegerField(choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс'), (5, '5 курс')], verbose_name='Курс')),
                ('year_start', models.IntegerField(verbose_name='Год поступления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная группа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['faculty', 'course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Студенческий билет')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('course', models.IntegerField(choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс'), (5, '5 курс')], default=1, verbose_name='Курс')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('address', models.TextField(blank=True, verbose_name='Адрес проживания')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('study_status', models.CharField(choices=[('active', 'Обучается'), ('academic_leave', 'Академический отпуск'), ('expelled', 'Отчислен'), ('graduated', 'Выпускник'), ('transferred', 'Переведен')], default='active', max_length=20, verbose_name='Статус обучения')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_active_account', models.BooleanField(default=True, verbose_name='Активная учетная запись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='admin_panel.group', verbose_name='Группа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
