# Generated by Django 5.2.7 on 2025-10-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
    ]
