# Generated by Django 5.2.7 on 2025-10-16 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 20 цифр.", regex='^\\+?1?\\d{9,20}$')], verbose_name='Телефон'),
        ),
    ]
