# Generated by Django 5.2.7 on 2025-10-17 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(help_text='Код специальности в формате XX.XX.XX (например: 09.02.07)', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Код должен быть в формате XX.XX.XX (например: 09.02.07)', regex='^\\d{2}\\.\\d{2}\\.\\d{2}$')], verbose_name='Код специальности'),
        ),
    ]
