# Generated by Django 5.2.7 on 2025-10-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_faculty_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='professions',
            field=models.JSONField(blank=True, default=list, help_text='Список профессий для данной специальности', verbose_name='Профессии'),
        ),
    ]
