# Generated by Django 5.2.7 on 2025-10-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_faculty_professions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profession',
            field=models.CharField(blank=True, help_text='Выбранная профессия в рамках специальности', max_length=150, null=True, verbose_name='Профессия'),
        ),
    ]
