# Generated by Django 5.2.7 on 2025-10-17 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_student_profession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('backup_type', models.CharField(choices=[('manual', 'Ручная'), ('automatic', 'Автоматическая'), ('scheduled', 'По расписанию')], default='manual', max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('creating', 'Создается'), ('completed', 'Завершена'), ('failed', 'Ошибка'), ('deleted', 'Удалена')], default='creating', max_length=20, verbose_name='Статус')),
                ('tables_count', models.IntegerField(default=0, verbose_name='Количество таблиц')),
                ('records_count', models.BigIntegerField(default=0, verbose_name='Количество записей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
            ],
            options={
                'verbose_name': 'Резервная копия',
                'verbose_name_plural': 'Резервные копии',
                'ordering': ['-created_at'],
            },
        ),
    ]
