# Generated by Django 5.2.7 on 2025-10-17 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_backup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['faculty', 'profession', 'code'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
        migrations.RemoveField(
            model_name='group',
            name='year_start',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profession',
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем'),
        ),
        migrations.AddField(
            model_name='group',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AddField(
            model_name='group',
            name='graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата планируемого окончания'),
        ),
        migrations.AddField(
            model_name='group',
            name='profession',
            field=models.CharField(default='Не указана', help_text='Профессия в рамках специальности', max_length=150, verbose_name='Профессия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название специальности'),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.faculty', verbose_name='Специальность'),
        ),
    ]
