# Generated by Django 5.2.7 on 2025-10-27 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_subject_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=150, verbose_name='Профессия')),
                ('course', models.PositiveSmallIntegerField(choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс')], verbose_name='Курс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subject_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='admin_panel.faculty', verbose_name='Специальность')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='admin_panel.subject', verbose_name='Предмет')),
                ('teachers', models.ManyToManyField(blank=True, related_name='subject_assignments', to='admin_panel.teacher', verbose_name='Преподаватели')),
            ],
            options={
                'verbose_name': 'Предмет по курсу',
                'verbose_name_plural': 'Предметы по курсам',
                'ordering': ['faculty__name', 'profession', 'course', 'subject__name'],
                'unique_together': {('subject', 'faculty', 'profession', 'course')},
            },
        ),
    ]
