# Generated by Django 5.2.7 on 2025-11-07 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Начало недели')),
                ('lessons', models.JSONField(blank=True, default=dict, verbose_name='Занятия')),
                ('day_buildings', models.JSONField(blank=True, default=dict, verbose_name='Корпуса по дням')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_weeks', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_weeks', to='admin_panel.group', verbose_name='Группа')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_schedule_weeks', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем')),
            ],
            options={
                'verbose_name': 'Неделя расписания',
                'verbose_name_plural': 'Недели расписания',
                'ordering': ['group', 'week_start'],
                'unique_together': {('group', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleTeacherSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_key', models.CharField(max_length=32, verbose_name='День недели')),
                ('slot_id', models.CharField(max_length=32, verbose_name='Пара')),
                ('parity', models.CharField(choices=[('numerator', 'Числитель'), ('denominator', 'Знаменатель')], max_length=16, verbose_name='Тип недели')),
                ('subject_name', models.CharField(blank=True, max_length=150, verbose_name='Название предмета')),
                ('subject_short', models.CharField(blank=True, max_length=80, verbose_name='Короткое название')),
                ('lesson_type', models.CharField(blank=True, max_length=50, verbose_name='Тип занятия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_slots', to='admin_panel.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='admin_panel.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='admin_panel.teacher', verbose_name='Преподаватель')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_slots', to='admin_panel.scheduleweek', verbose_name='Неделя')),
            ],
            options={
                'verbose_name': 'Занятость преподавателя',
                'verbose_name_plural': 'Занятость преподавателей',
                'indexes': [models.Index(fields=['teacher', 'day_key', 'slot_id', 'parity'], name='admin_panel_teacher_5e0676_idx'), models.Index(fields=['week', 'day_key'], name='admin_panel_week_id_dad898_idx')],
                'unique_together': {('teacher', 'week', 'day_key', 'slot_id', 'parity')},
            },
        ),
    ]
