# Generated by Django 5.2.7 on 2025-11-08 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_scheduleweek_scheduleteacherslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email запроса')),
                ('role', models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель')], max_length=16, verbose_name='Тип пользователя')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processed', 'Обработана'), ('rejected', 'Отклонена')], default='pending', max_length=16, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_password_requests', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_requests', to='admin_panel.student', verbose_name='Студент')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_requests', to='admin_panel.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Запрос на восстановление пароля',
                'verbose_name_plural': 'Запросы на восстановление пароля',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student',), name='unique_pending_student_password_request'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('teacher',), name='unique_pending_teacher_password_request')],
            },
        ),
    ]
