# Generated by Django 5.2.7 on 2025-11-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_alter_graderecord_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='graderecord',
            name='grade_type',
            field=models.CharField(blank=True, choices=[('', 'Без типа'), ('practice', 'Практическая работа'), ('lab', 'Лабораторная работа'), ('homework', 'Домашнее задание'), ('test', 'Контрольная/тест'), ('oral', 'Устный опрос'), ('project', 'Проект/защита'), ('other', 'Другое')], max_length=50, verbose_name='Тип оценки'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='lesson_topic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тема занятия'),
        ),
    ]
