# Generated by Django 5.2.7 on 2025-11-15 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_graderecord_grade_type_graderecord_lesson_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='graderecord',
            name='grade_type',
            field=models.CharField(blank=True, choices=[('', 'Без типа'), ('lecture', 'Лекция'), ('practice', 'Практическая работа'), ('test', 'Тест'), ('oral', 'Устный опрос'), ('project', 'Проект')], max_length=50, verbose_name='Тип оценки'),
        ),
        migrations.CreateModel(
            name='GradeColumnContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(verbose_name='Дата занятия')),
                ('slot_id', models.CharField(blank=True, default='', max_length=20, verbose_name='Пара')),
                ('grade_type', models.CharField(blank=True, choices=[('', 'Без типа'), ('lecture', 'Лекция'), ('practice', 'Практическая работа'), ('test', 'Тест'), ('oral', 'Устный опрос'), ('project', 'Проект')], max_length=50, verbose_name='Тип оценки')),
                ('lesson_topic', models.CharField(blank=True, max_length=255, verbose_name='Тема занятия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_column_contexts', to='admin_panel.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_column_contexts', to='admin_panel.teacher', verbose_name='Преподаватель')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_grade_column_contexts', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Контекст колонки журнала',
                'verbose_name_plural': 'Контексты колонок журнала',
                'ordering': ['lesson_date', 'slot_id'],
                'unique_together': {('teacher', 'group', 'lesson_date', 'slot_id')},
            },
        ),
    ]
